<?php

namespace AKlump\HtaccessManager\Tests\Unit\Plugin\Helper;

use AKlump\HtaccessManager\Helper\SplitHeader;
use PHPUnit\Framework\TestCase;

/**
 * @covers \AKlump\HtaccessManager\Helper\SplitHeader
 */
class SplitHeaderTest extends TestCase {

  public function testInvoke() {
    $content = <<<EOD
    #
    #
    # Staging .htaccess for Drupal 7 webroot
    #
    # THIS FILE IS AUTOGENERATED; DO NOT MODIFY.
    # (Built on: 2024-11-21T01:10:05+00:00)
    # @see /Users/aklump/Code/Packages/php/htaccess_manager/htaccess_manager.php

    Deny from 0.0.0.0
    
    EOD;
    list($header, $body) = (new SplitHeader())($content);
    $expected_header = <<<EOD
    #
    #
    # Staging .htaccess for Drupal 7 webroot
    #
    # THIS FILE IS AUTOGENERATED; DO NOT MODIFY.
    # (Built on: 2024-11-21T01:10:05+00:00)
    # @see /Users/aklump/Code/Packages/php/htaccess_manager/htaccess_manager.php
    EOD;
    $this->assertSame($expected_header, $header);
    $this->assertSame("Deny from 0.0.0.0\n", $body);
  }
}
