<?php

namespace AKlump\HtaccessManager\Config;

class Defaults {

  const OUTPUT_FILE_ID = 'MISSING ID';

  const OUTPUT_FILE_TITLE = 'UNTITLED';

  const OUTPUT_FILE_HEADER = 'THIS FILE IS AUTOGENERATED; DO NOT MODIFY.';

}
