<?php

namespace AKlump\HtaccessManager\Plugin;

use Symfony\Component\HttpFoundation\Response;

class WriteErrorHandler {

  public function __invoke(int $status, string $filepath) {
    $message = Response::$statusTexts[$status] ?? 'Unknown Error';
    $php_script = <<<PHP
        <?php
        /**
         * @file Serve a fast $status response
         *
         * This is auto-generated by aklump/htaccess-manager.  DO NOT EDIT!
         */
        declare(strict_types=1);
        
        http_response_code($status);
        header('Content-Type: text/plain; charset=UTF-8');
        header('Content-Language: en');
        header('Cache-Control: max-age=600, public');
        header('X-Robots-Tag: noindex, nofollow');
        
        echo '$status $message' . PHP_EOL;
        exit;
        PHP;
    if (@file_put_contents($filepath, $php_script) === FALSE) {
      throw new \RuntimeException(sprintf('Failed to write error handler file: %s', $filepath));
    }
  }
}
