<?php

namespace AKlump\HtaccessManager\Tests\Unit\Plugin;

use AKlump\HtaccessManager\Plugin\FileHeader;
use PHPUnit\Framework\TestCase;

/**
 * @covers \AKlump\HtaccessManager\Plugin\FileHeader
 * @uses \AKlump\HtaccessManager\Config\Defaults
 */
class FileHeaderTest extends TestCase {

  public function testInvokeWithFullContext() {
    $resource = fopen('php://memory', 'r+');
    $plugin = new FileHeader();
    $output_file_config = ['title' => 'Custom Title'];
    $context = [
      'config' => ['header' => 'Custom Header'],
      'file_header' => ['@see' => 'https://example.com'],
    ];

    $plugin($resource, $output_file_config, $context);

    rewind($resource);
    $content = stream_get_contents($resource);
    fclose($resource);

    $this->assertStringContainsString('# Custom Title', $content);
    $this->assertStringContainsString('# CUSTOM HEADER', $content);
    $this->assertStringContainsString('# (Built on:', $content);
    $this->assertStringContainsString('# @see https://example.com', $content);
  }

  public function testInvokeWithDefaults() {
    $resource = fopen('php://memory', 'r+');
    $plugin = new FileHeader();
    $output_file_config = [];
    $context = [];

    $plugin($resource, $output_file_config, $context);

    rewind($resource);
    $content = stream_get_contents($resource);
    fclose($resource);

    $this->assertStringContainsString('# UNTITLED', $content);
    $this->assertStringContainsString('# THIS FILE IS AUTOGENERATED; DO NOT MODIFY.', $content);
  }

  public function testEmptyHeaderSuppressesOutput() {
    $resource = fopen('php://memory', 'r+');
    $plugin = new FileHeader();
    $output_file_config = [];
    $context = [
      'config' => ['header' => ''],
    ];

    $plugin($resource, $output_file_config, $context);

    rewind($resource);
    $content = stream_get_contents($resource);
    fclose($resource);

    $this->assertStringNotContainsString('THIS FILE IS AUTOGENERATED', $content);
  }

  public function testGetName() {
    $this->assertEquals('File Header', (new FileHeader())->getName());
  }

  public function testGetPriority() {
    $this->assertEquals(100, FileHeader::getPriority());
  }
}
